version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tick_network
    restart: unless-stopped

  php:
    image: wordpress:php8.2-fpm
    container_name: php_fpm
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - tick_network
    depends_on:
      - db
    restart: unless-stopped


  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tick_network
    depends_on:
      - php
    restart: unless-stopped
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - tick_network

  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    depends_on:
      - influxdb
    networks:
      - tick_network

  chronograf:
    image: chronograf:1.10
    container_name: chronograf
    ports:
      - "8888:8888"
    environment:
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_USERNAME: admin
      INFLUXDB_PASSWORD: password123
    depends_on:
      - influxdb
    networks:
      - tick_network

  kapacitor:
    image: kapacitor:1.6
    container_name: kapacitor
    ports:
      - "9092:9092"
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_PASSWORD=my-super-secret-auth-token
      - KAPACITOR_INFLUXDB_0_USERNAME=admin
      - KAPACITOR_INFLUXDB_0_TIMEOUT=30s
      - KAPACITOR_INFLUXDB_SUBSCRIPTION_PROTOCOL=http
      - KAPACITOR_INFLUXDB_DISABLE_SUBSCRIPTIONS=true
      - KAPACITOR_INFLUXDB_0_INSECURE_SKIP_VERIFY=true
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./scripts:/etc/kapacitor/scripts 
    depends_on:
      - influxdb
    networks:
      - tick_network

volumes:
  influxdb_data:
  mysql_data:

networks:
  tick_network:
    driver: bridge
